service: sheppit-lambda-s3-publisher

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    S3_DESTINATION_BUCKET: ${file(./config.yml):required.S3_DESTINATION_BUCKET}
    CLOUDFRONT_DISTRIBUTION_ID: ${file(./config.yml):optional.CLOUDFRONT_DISTRIBUTION_ID}
    GIT_WEBSITE_PREFIX_PATH: ${file(./config.yml):optional.GIT_WEBSITE_PREFIX_PATH}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetBucketLocation
        - s3:ListBucket
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::${self:provider.environment.S3_DESTINATION_BUCKET}/*
        - arn:aws:s3:::${self:provider.environment.S3_DESTINATION_BUCKET}
    - Effect: Allow
      Action:
        - cloudfront:CreateInvalidation
      Resource:
        - '*' # Cloudfront doesn't allow resource IAM permissions

package:
 include:
   - app
   - node_modules

functions:
  githubListen:
    handler: app/handler.githubListen
    events:
      - sns: sheppit-listen
